#!/usr/bin/env python3
"""Generate the artist-facing PFM catalog from the live engine registry."""

from __future__ import annotations

import argparse
import html
import sys
from collections import OrderedDict
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
OUTPUT = ROOT / "web" / "static" / "docs" / "reference.html"
PREVIEWS = ROOT / "web" / "static" / "pfm-previews"
CUSTOM_PFM_PREFIXES = ("shape_dither_custom_", "tessellation_custom_")

FAMILY_NAMES = {
    "voronoi": "Voronoi",
    "lbg": "LBG",
    "adaptive": "Adaptive",
    "poisson": "Poisson-disk",
    "grid": "Grid & random",
    "tessellation": "Tessellations",
    "spiral": "Spiral",
    "hatch": "Hatch",
    "sketch": "Sketch",
    "streamline": "Streamlines",
    "composite": "Composite & mosaic",
    "dither": "Dither",
    "shape_dither": "Shape Dither",
    "packing": "Packing",
    "growth": "Growth",
}

FAMILY_GUIDANCE = {
    "voronoi": "Relaxed sites give the most polished all-purpose point rhythm.",
    "lbg": "Split-and-merge sampling produces a disciplined halftone structure.",
    "adaptive": "Direct tone-to-spacing sampling is quick, organic, and excellent for drafts.",
    "poisson": "Blue-noise sampling enforces a hard minimum distance without relaxation.",
    "grid": "Direct screens and random marks with short, predictable generation times.",
    "tessellation": "Periodic vector motifs change geometry with the source tone.",
    "spiral": "One continuous groove carries tone with very few pen lifts.",
    "hatch": "Parallel or crossed strokes make bold, economical plotted tone.",
    "sketch": "Layered gestural strokes imitate pencil and scribble textures.",
    "streamline": "Curves follow mathematical, image-derived, or painted direction fields.",
    "composite": "Combine modules or subdivide the page into local drawing systems.",
    "dither": "Error diffusion turns grayscale into a binary pen texture.",
    "shape_dither": "Quantized image cells stamp scalable symbols or custom SVG artwork.",
    "packing": "Tone controls circles packed into the available space.",
    "growth": "Iterative self-avoiding curves form dense organic structures.",
}


def builtin_pfms(registry) -> list:
    """Return only the fixed catalog; installed custom styles are documented in-app."""
    return [
        pfm for pfm in registry.values()
        if not pfm.id.startswith(CUSTOM_PFM_PREFIXES)
    ]


def esc(value) -> str:
    return html.escape(str(value), quote=True)


def constraint_text(param) -> str:
    if param.choices:
        return "choices: " + " · ".join(map(str, param.choices))
    parts = []
    if param.min is not None:
        parts.append(f"min {param.min}")
    if param.max is not None:
        parts.append(f"max {param.max}")
    if param.step is not None:
        parts.append(f"step {param.step}")
    return " · ".join(parts) or "—"


def parameter_rows(pfm) -> str:
    rows = []
    for param in pfm.params:
        rows.append(
            f'        <tr data-param="{esc(param.name)}">'
            f'<td>{esc(param.group)}</td><td><strong>{esc(param.label)}</strong>'
            f'<code>{esc(param.name)}</code></td><td>{esc(param.type)}</td>'
            f'<td>{esc(param.default)}</td><td>{esc(constraint_text(param))}</td>'
            f'<td>{esc(param.help)}</td></tr>'
        )
    return "\n".join(rows)


def pfm_entry(pfm) -> str:
    preview = PREVIEWS / f"{pfm.id}.png"
    if preview.exists():
        visual = (
            f'      <img class="pfm-reference-preview" loading="lazy" '
            f'src="../pfm-previews/{esc(pfm.id)}.png" '
            f'alt="Preview generated by {esc(pfm.name)}.">'
        )
    else:
        visual = (
            '      <div class="pfm-reference-missing" role="img" '
            f'aria-label="No preview is available for {esc(pfm.name)}.">Preview pending</div>'
        )
    return f'''    <article class="pfm-entry" id="pfm-{esc(pfm.id)}" data-search="{esc(pfm.name.lower())} {esc(pfm.family)} {esc(pfm.style)}">
      <header class="pfm-entry-head">
        <div><span class="pfm-family-label">{esc(FAMILY_NAMES.get(pfm.family, pfm.family.title()))}</span><h3>{esc(pfm.name)}</h3><code>{esc(pfm.id)}</code></div>
        <a href="#pfm-{esc(pfm.id)}" aria-label="Link to {esc(pfm.name)}">#</a>
      </header>
      <div class="pfm-reference-body">
{visual}
        <div class="pfm-parameter-wrap">
          <table class="parameter-table">
            <thead><tr><th>Group</th><th>Parameter</th><th>Type</th><th>Default</th><th>Range / choices</th><th>What it changes</th></tr></thead>
            <tbody>
{parameter_rows(pfm)}
            </tbody>
          </table>
        </div>
      </div>
    </article>'''


def render_reference() -> str:
    from engine.pfm import REGISTRY

    catalog_pfms = builtin_pfms(REGISTRY)
    families: OrderedDict[str, list] = OrderedDict()
    for pfm in catalog_pfms:
        families.setdefault(pfm.family, []).append(pfm)

    family_links = "\n".join(
        f'  <a class="card" href="#family-{esc(family)}"><strong>{esc(FAMILY_NAMES.get(family, family.title()))}</strong><p>{len(pfms)} style{"s" if len(pfms) != 1 else ""}</p></a>'
        for family, pfms in families.items()
    )
    sections = []
    for family, pfms in families.items():
        sections.append(
            f'''<section class="pfm-family" id="family-{esc(family)}">
  <h2>{esc(FAMILY_NAMES.get(family, family.title()))}</h2>
  <p>{esc(FAMILY_GUIDANCE.get(family, "A registered PlotterForge path-finding family."))}</p>
{chr(10).join(pfm_entry(pfm) for pfm in pfms)}
</section>'''
        )

    return f'''<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="Search all {len(catalog_pfms)} built-in PlotterForge path-finding modules and inspect every parameter, default, range, choice, and help description.">
<title>PFM reference · PlotterForge Manual</title>
<link rel="stylesheet" href="docs.css">
<script src="docs.js" defer></script>
</head>
<body>
<main class="wrap reference-page">

<nav class="crumbs"><a href="index.html">Manual</a> › PFM reference</nav>

<header class="hero">
  <div class="kicker">PlotterForge · Generated reference</div>
  <h1>Every built-in style, from the source of truth</h1>
  <p class="lede">This catalog is generated from the same typed schemas that build the application controls. It currently contains {len(catalog_pfms)} built-in PFMs; defaults, limits and choices cannot silently drift away from the engine.</p>
</header>

<div class="note"><strong>How to use this page:</strong> begin with <a href="choose-a-style.html">Choose a style</a>, then search here for the exact control. Custom Cavalry and uploaded Shape Dither styles appear in your installation but are not part of this built-in catalog.</div>

<label class="reference-filter-label" for="pfm-reference-filter">Filter the catalog</label>
<input id="pfm-reference-filter" class="reference-filter" type="search" placeholder="Try “stipple”, “tone”, “streamline”…" autocomplete="off">
<p id="pfm-reference-count" class="muted">Showing all {len(catalog_pfms)} styles.</p>

<div class="cards reference-families">
{family_links}
</div>

{chr(10).join(sections)}

<footer>Generated from <code>engine.pfm.REGISTRY</code>. Rebuild with <code>.venv/bin/python tools/build_docs_reference.py</code>.</footer>

</main>
<script>
document.addEventListener("DOMContentLoaded", () => {{
  const input = document.getElementById("pfm-reference-filter");
  const entries = Array.from(document.querySelectorAll(".pfm-entry"));
  const count = document.getElementById("pfm-reference-count");
  input.addEventListener("input", () => {{
    const terms = input.value.toLowerCase().trim().split(/\\s+/).filter(Boolean);
    let visible = 0;
    for (const entry of entries) {{
      const text = (entry.dataset.search + " " + entry.textContent).toLowerCase();
      const match = terms.every((term) => text.includes(term));
      entry.hidden = !match;
      if (match) visible += 1;
    }}
    count.textContent = terms.length ? `Showing ${{visible}} matching styles.` : "Showing all {len(catalog_pfms)} styles.";
  }});
}});
</script>
</body>
</html>
'''


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail when the checked-in reference is stale")
    parser.add_argument("--output", type=Path, default=OUTPUT, help="output HTML path")
    args = parser.parse_args(argv)
    rendered = render_reference()
    if args.check:
        if not args.output.exists() or args.output.read_text(encoding="utf-8") != rendered:
            print(f"stale generated documentation: {args.output}", file=sys.stderr)
            return 1
        print(f"PFM reference is current: {args.output}")
        return 0
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(rendered, encoding="utf-8")
    print(f"wrote {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
